### ISSUE TITLE
Auto Close OSD broken

### ISSUE THREAD

**Issue by JFG1000** [SerpentDrago/skin.auramod#221]
Just wanted to let you know for some odd reason it's broken again even after updating skin helper service, it worked to begin with but it's now no longer working when using Kodi today

EDIT I've done some further testing and it appears sometimes it works after a kodi restart and sometimes it just doesn't work at all, bit of a strange bug 

Nvidia Shield Pro
Kodi 19.3

**Comment by inb4after** [comment]
@JFG1000 

Please upload two fresh logfiles:

1. Auto-close OSD works after a Kodi restart
2. Auto-close OSD does not work after a Kodi restart

Then we can compare and narrow down this issue.

**Comment by JFG1000** [comment]
Ok I will do this for you when I next get a chance

**Comment by JFG1000** [comment]
https://paste.kodi.tv/ejexicucis

Log file with it working, will try get the other log when it next bugs out

EDIT : Here is the log of when it bugs out, excuse the trakt cache clears as trakt was having problems on my shield at the time.

https://paste.kodi.tv/buravuvesu

**Comment by inb4after** [comment]
Unfortunately there is not much debug info from Skin Helper Service to make it immediately obvious what the problem is, however:

```
2021-12-20 18:20:05.725 T:8002  WARNING <general>: Skin Helper Service --> Exception details: Type: ImportError Value: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770. Traceback: Traceback (most recent call last):
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
                                                       from _multiprocessing import SemLock, sem_unlink
                                                   ImportError: cannot import name 'sem_unlink' from '_multiprocessing' (unknown location)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/kodi_monitor.py", line 63, in onNotification
                                                       self.reset_win_props()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/kodi_monitor.py", line 129, in reset_win_props
                                                       self.metadatautils.process_method_on_list(self.win.clearProperty, self.all_window_props)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 302, in process_method_on_list
                                                       return self._process_method_on_list(*args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 232, in process_method_on_list
                                                       pool = ThreadPool()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
                                                       Pool.__init__(self, processes, initializer, initargs)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
                                                       self._change_notifier = self._ctx.SimpleQueue()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
                                                       return SimpleQueue(ctx=self.get_context())
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
                                                       self._rlock = ctx.Lock()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/context.py", line 67, in Lock
                                                       from .synchronize import Lock
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
                                                       raise ImportError("This platform lacks a functioning sem_open" +
                                                   ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
                                                   
2021-12-20 18:20:05.725 T:8002    ERROR <general>: Skin Helper Service --> Exception in resources.lib.kodi_monitor ! --> This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

It is probably related to this error from Skin Helper Service. 

It could be that the addon can no longer detect if VideoOSD.xml is being opened. This bug is inconsistent and very hard to reproduce as it only affects Android devices specifically and requires lots of restarting Kodi until it breaks/works.

I will open an issue thread on their Github for further investigation.

**Comment by JFG1000** [comment]
Ok thankyou for looking into this and opening the issue on there github for me it's much appreciated. Hopefully it can be fixed as it's been fine up til now

**Comment by SerpentDrago** [comment]
The real solution is prob to do what jurial did and get away from skin helper to do this . 

This is the commit where he added it to Eminence 2

https://github.com/jurialmunkey/skin.eminence.2/commit/6b5b74fd0fe348b9e69eee4f0ae2801bb8a79a60
https://github.com/jurialmunkey/skin.eminence.2/issues/91#issuecomment-939212727

**Comment by inb4after** [comment]
@JFG1000

This error is from script.module.metadatautils which is a dependancy of Skin Helper Service. There was an update to metadatautils to fix some Kodi 19.2 multiprocessing errors.

Please could you test the following:

1. Auto-close OSD is broken
2. Update metadatautils through the dependancy menu (It is named as "Metadata and Artwork module") to 1.0.44
3. Restart Kodi
4. Check if Auto-close OSD is fixed
5. Continue using auto-close OSD to ensure the issue does not return after any amount of Kodi restarts

You can follow our discussion in [this](https://github.com/kodi-community-addons/script.skin.helper.service/issues/149) issue thread.

**Comment by JFG1000** [comment]
Ok great thankyou for the response, I've updated and will continue to test.

**Comment by JFG1000** [comment]
UPDATE : it appears this issue is now resolved, will close this issue now and will re open if the issue ever persists. Many thanks
